#!/usr/bin/env bash

configured_dir=${NOTES_DIRECTORY%/} # Remove trailing slashes
notes_dir="${configured_dir:-$HOME/notes}"
escaped_notes_dir=$(printf $notes_dir | sed -e 's/[]\/$*.^|[]/\\&/g')

if [ "$NOTES_EDITOR" ]; then
    # Allow user to specify separate editor specifically for notes
    EDITOR="$NOTES_EDITOR"
elif [ -z "$EDITOR" ] && type editor &>/dev/null; then
    # If no $EDITOR, look for `editor` (symlink on debian/ubuntu/etc)
    EDITOR=editor
fi

without_notes_dir() {
    cat | sed -e s/^$escaped_notes_dir//g | sed -E "s/^\/+//g"
}

find_notes() {
    find_output=$(find "$notes_dir" -ipath "$notes_dir/*$**" -type f 2>&1)
    find_result=$?
    formatted_output=$(printf "$find_output" | without_notes_dir)

    if [[ $find_result == 0 && "$formatted_output" ]]; then
        printf "$formatted_output\n"
        return 0
    else
        return 2
    fi
}

grep_notes() {
    if [ ! "$#" -gt 0 ]; then
        printf "Grep requires a pattern, but none was provided."
        return 1
    fi

    grep_output=$(grep -r "$notes_dir" -li -e "$*" 2>&1)
    grep_result=$?
    formatted_output=$(printf "$grep_output" | without_notes_dir)

    if [[ $grep_result == 0 && "$formatted_output" ]]; then
        printf "$formatted_output\n"
        return 0
    else
        return 2
    fi
}

new_note() {
    note_name="$*"
    mkdir -p $(dirname "$notes_dir/$note_name")
    open_note "$note_name.md"
}

open_something() {
    if [[ -p /dev/stdin ]]; then
        read -d'\n' note_names
        while read note_name; do
            open_note "$note_name"
        done <<< "$note_names"
    elif [ $# -gt 0 ]; then
        open_note "$*"
    else
        open $notes_dir
    fi
}

open_note() {
    note_path=$1

    if [[ "$note_path" != *.md ]]; then
        note_path="$note_path.md"
    fi
    if [ ! -f "$note_path" ]; then
        note_path="$notes_dir/$note_path"
    fi
    if [ -z "$EDITOR" ]; then
        printf "Please set \$EDITOR to edit notes\n"
        exit 1
    fi

    $EDITOR "$note_path" < /dev/tty
}

usage() {
	cat <<EOF
notes is a command line note taking tool.

Usage:
    notes new|n <name>                    # Create a new note
    notes find|f [pattern]                # Search notes by filename and path
    notes grep|g <pattern>                # Search notes by content
    notes open|o                          # Open your notes directory
    notes open|o <name>                   # Open a note for editing by full name
    echo <name> | notes open|o            # Open all note filenames piped in
    notes --help                          # Print this usage information

'command|c' means you can use 'command' or the equivalent shorthand alias 'c'

Your notes directory is $notes_dir. You can
override this by setting \$NOTES_DIRECTORY to your preferred path.
EOF
}

main() {
    ret=0
    cmd=""

    if [ -z "$1" ]; then
        printf "No command specified\n\n"
        usage
        exit 1
    fi

    case "$1" in
        "new"|"n" )
            cmd="new_note"
            ;;
        "find"|"f" )
            cmd="find_notes"
            ;;
        "grep"|"g" )
            cmd="grep_notes"
            ;;
        "open"|"o" )
            cmd="open_something"
            ;;
        --help | -help | -h )
            cmd="usage"
            ;;
        * )
            printf "$1 is not a recognized notes command.\n\n"
            cmd="usage"
            ret=1
            ;;
    esac
    shift

    $cmd $@
    ret=$[$ret+$?]
    exit $ret
}
main "$@"
